/**
 * A5b-0 root-declaration ownership matrix coverage (review-driven closure).
 *
 * The reviewer of A5b-0..4 asked for DURABLE evidence that every root-scope
 * declaration of `startRunner()` has an explicit ownership classification — the
 * gap that let submission policy (`attachmentRefusal`, ...) stay in the
 * composition root unnoticed. `test/a5b-root-declaration-matrix.json` holds one
 * classified row per declaration (generated by `temp/a5b-matrix.mjs`); this test
 * keeps that artifact honest:
 *
 * - the matrix must cover EXACTLY the declarations `src/app/bootstrap.ts`
 *   declares today (a new/renamed/moved declaration fails until the matrix is
 *   regenerated);
 * - every classification must come from the plan §7.6.1 category set;
 * - the `MUST_MOVE:*` residual may only SHRINK (A5b-5 moves the surface rows,
 *   A5b-6 the submission rows; the final A5b state has none).
 */
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'
import ts from 'typescript'

const bootstrapSource = readFileSync(new URL('../src/app/bootstrap.ts', import.meta.url), 'utf8')
const matrix = JSON.parse(
  readFileSync(new URL('./a5b-root-declaration-matrix.json', import.meta.url), 'utf8'),
) as {
  readonly generatedFrom: string
  readonly total: number
  readonly rows: ReadonlyArray<{
    readonly name: string
    readonly classification: string
    readonly mutable: boolean
    readonly lines: string
    readonly hostDependency: boolean
  }>
}

/** The residual ledger as of the A5b-0..4 closure. It is SHRINK-ONLY. */
const RESIDUAL_LEDGER = new Set([
  // A5b-5 owns the application-event adapter + client actions.
  'surfaceEvents',
  'runClipboardCommand',
  'clipboardEnv',
  'runCopyCommand',
  'copyEnv',
  'openRewindPicker',
  // A5b-6 closure.
  'submissionWriterSection',
])

const ALLOWED = new Set([
  'KEEP_BOOTSTRAP:process-cordis-prerequisite',
  'KEEP_BOOTSTRAP:host-service-resolution',
  'KEEP_BOOTSTRAP:owner-construction-or-bind',
  'KEEP_BOOTSTRAP:startup-resume-create-orchestration',
  'KEEP_BOOTSTRAP:owner-connector',
  'KEEP_BOOTSTRAP:mount-dispose-fatal-coordination',
  'MUST_MOVE:app-surface',
  'MUST_MOVE:app-submission',
  'MUST_MOVE:app-command',
  'MUST_MOVE:app-session',
  'MUST_MOVE:app-direct',
  'CLIENT_LOCAL_HELPER_ALREADY_OWNED',
])

/** Every root-scope declaration name inside `startRunner()`, in source order. */
function rootDeclarations(): string[] {
  const sf = ts.createSourceFile('bootstrap.ts', bootstrapSource, ts.ScriptTarget.ESNext, true, ts.ScriptKind.TS)
  let startRunner: ts.Node | undefined
  const find = (node: ts.Node): void => {
    if (ts.isVariableDeclaration(node) && ts.isIdentifier(node.name) && node.name.text === 'startRunner') startRunner = node.initializer
    ts.forEachChild(node, find)
  }
  find(sf)
  assert.ok(startRunner !== undefined, 'startRunner must exist')
  assert.ok(
    ts.isArrowFunction(startRunner) || ts.isFunctionExpression(startRunner),
    'startRunner must be a function',
  )
  const { body } = startRunner
  assert.ok(ts.isBlock(body), 'startRunner must have a block body')
  const names: string[] = []
  const bind = (nameNode: ts.Node): void => {
    if (ts.isIdentifier(nameNode)) names.push(nameNode.text)
    else ts.forEachChild(nameNode, bind)
  }
  for (const stmt of body.statements) {
    if (ts.isVariableStatement(stmt)) {
      for (const d of stmt.declarationList.declarations) bind(d.name)
    } else if ((ts.isFunctionDeclaration(stmt) || ts.isClassDeclaration(stmt) || ts.isTypeAliasDeclaration(stmt) || ts.isInterfaceDeclaration(stmt)) && stmt.name) {
      names.push(stmt.name.text)
    }
  }
  return names
}

test('A5b-0 matrix: every root declaration of startRunner() is classified', () => {
  const declared = rootDeclarations()
  const classified = matrix.rows.map((r) => r.name)
  assert.equal(classified.length, matrix.total, 'the matrix total must match its rows')
  assert.deepEqual(
    [...new Set(declared)].sort(),
    [...new Set(classified)].sort(),
    'the ownership matrix must cover EXACTLY the declarations bootstrap declares today (regenerate temp/a5b-matrix.mjs --write --commit-artifact when this changes)',
  )
  for (const row of matrix.rows) {
    assert.ok(ALLOWED.has(row.classification), `${row.name} has an unknown classification: ${row.classification}`)
    assert.notEqual(row.classification, '', `${row.name} must be classified`)
  }
})

test('A5b-0 matrix: the residual ownership ledger only shrinks', () => {
  const residual = matrix.rows.filter((r) => r.classification.startsWith('MUST_MOVE:')).map((r) => r.name)
  for (const name of residual) {
    assert.ok(
      RESIDUAL_LEDGER.has(name),
      `${name} is a NEW unowned root declaration: classify it as KEEP_BOOTSTRAP with a §7.6.1 reason, or move it to its owner (the ledger may not grow)`,
    )
  }
})
