/**
 * A5b-0 root-declaration ownership matrix coverage (review-driven closure).
 *
 * The reviewer of A5b-0..4 asked for DURABLE evidence that every root-scope
 * declaration of `startRunner()` has an explicit ownership classification — the
 * gap that let submission policy (`attachmentRefusal`, ...) stay in the
 * composition root unnoticed. `test/a5b-root-declaration-matrix.json` holds one
 * classified row per declaration (generated by `scripts/a5b-root-matrix.mjs`);
 * this test keeps that artifact honest:
 *
 * - the matrix must cover EXACTLY the declarations `src/app/bootstrap.ts`
 *   declares today (a new/renamed/moved declaration fails until the matrix is
 *   regenerated);
 * - every classification must come from the plan §7.6.1 category set;
 * - the `MUST_MOVE:*` residual may only SHRINK (A5b-5 moves the surface rows,
 *   A5b-6 the submission rows; the final A5b state has none).
 */
import assert from 'node:assert/strict'
import { spawnSync } from 'node:child_process'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import test from 'node:test'
import ts from 'typescript'

const REPO_ROOT = fileURLToPath(new URL('..', import.meta.url))

const bootstrapSource = readFileSync(new URL('../src/app/bootstrap.ts', import.meta.url), 'utf8')
const matrix = JSON.parse(
  readFileSync(new URL('./a5b-root-declaration-matrix.json', import.meta.url), 'utf8'),
) as {
  readonly generatedFrom: string
  readonly total: number
  readonly rows: ReadonlyArray<{
    readonly name: string
    readonly classification: string
    readonly owner: string
    readonly lifecycle: string
    readonly capabilities: string
    readonly callers: readonly string[]
    readonly mutable: boolean
    readonly lines: string
    readonly hostDependency: boolean
    readonly sweep: string
    readonly sweepNote: string
  }>
}

/** The residual ledger after A5b-6. It is EXACT: any new MUST_MOVE row is an
 *  unclassified business handler and fails immediately. */
const RESIDUAL_LEDGER = new Set<string>()

/** The A5b-6 zero-assumption sweep verdict every remaining row must carry. */
const SWEEP_VERDICT = 'verified@a5b6'

const ALLOWED = new Set([
  'KEEP_BOOTSTRAP:process-cordis-prerequisite',
  'KEEP_BOOTSTRAP:host-service-resolution',
  'KEEP_BOOTSTRAP:owner-construction-or-bind',
  'KEEP_BOOTSTRAP:startup-resume-create-orchestration',
  'KEEP_BOOTSTRAP:owner-connector',
  'KEEP_BOOTSTRAP:mount-dispose-fatal-coordination',
  'MUST_MOVE:app-surface',
  'MUST_MOVE:app-submission',
  'MUST_MOVE:app-command',
  'MUST_MOVE:app-session',
  'MUST_MOVE:app-direct',
  'CLIENT_LOCAL_HELPER_ALREADY_OWNED',
])

/** Every root-scope declaration name inside `startRunner()`, in source order. */
function rootDeclarations(): string[] {
  const sf = ts.createSourceFile('bootstrap.ts', bootstrapSource, ts.ScriptTarget.ESNext, true, ts.ScriptKind.TS)
  let startRunner: ts.Node | undefined
  const find = (node: ts.Node): void => {
    if (ts.isVariableDeclaration(node) && ts.isIdentifier(node.name) && node.name.text === 'startRunner') startRunner = node.initializer
    ts.forEachChild(node, find)
  }
  find(sf)
  assert.ok(startRunner !== undefined, 'startRunner must exist')
  assert.ok(
    ts.isArrowFunction(startRunner) || ts.isFunctionExpression(startRunner),
    'startRunner must be a function',
  )
  const { body } = startRunner
  assert.ok(ts.isBlock(body), 'startRunner must have a block body')
  const names: string[] = []
  const bind = (nameNode: ts.Node): void => {
    if (ts.isIdentifier(nameNode)) names.push(nameNode.text)
    else ts.forEachChild(nameNode, bind)
  }
  for (const stmt of body.statements) {
    if (ts.isVariableStatement(stmt)) {
      for (const d of stmt.declarationList.declarations) bind(d.name)
    } else if ((ts.isFunctionDeclaration(stmt) || ts.isClassDeclaration(stmt) || ts.isTypeAliasDeclaration(stmt) || ts.isInterfaceDeclaration(stmt)) && stmt.name) {
      names.push(stmt.name.text)
    }
  }
  return names
}

test('A5b-0 matrix: every root declaration of startRunner() is classified', () => {
  const declared = rootDeclarations()
  const classified = matrix.rows.map((r) => r.name)
  assert.equal(classified.length, matrix.total, 'the matrix total must match its rows')
  assert.deepEqual(
    [...new Set(declared)].sort(),
    [...new Set(classified)].sort(),
    'the ownership matrix must cover EXACTLY the declarations bootstrap declares today (regenerate with `node scripts/a5b-root-matrix.mjs --write`)',
  )
  for (const row of matrix.rows) {
    assert.ok(ALLOWED.has(row.classification), `${row.name} has an unknown classification: ${row.classification}`)
    assert.notEqual(row.classification, '', `${row.name} must be classified`)
    assert.notEqual(row.owner, '', `${row.name} must name its owner (or 'bootstrap')`)
    assert.notEqual(row.capabilities, '', `${row.name} must record its capability set`)
    // The plan §6.1 fields a slice needs to actually execute a move: the
    // residual rows and the non-trivial owner connectors must carry a
    // lifecycle story, not just a category.
    if (row.classification.startsWith('MUST_MOVE:') || row.classification === 'KEEP_BOOTSTRAP:owner-connector') {
      assert.ok(row.lifecycle !== '' && !row.lifecycle.startsWith('n/a'),
        `${row.name} (${row.classification}) must record its lifecycle ownership`)
    }
    // A5b-6 zero-assumption sweep: the audit is a DURABLE per-row artifact, not
    // a report sentence. Every remaining declaration must carry the verdict and
    // a concrete §7.6.1 justification, so a silent keep cannot pass.
    assert.equal(row.sweep, SWEEP_VERDICT, `${row.name} must carry the A5b-6 sweep verdict (${SWEEP_VERDICT})`)
    assert.ok(row.sweepNote.length >= 20, `${row.name} must carry a concrete A5b-6 sweep justification`)
    assert.equal(row.sweepNote.startsWith('n/a'), false, `${row.name} sweep note must justify the keep, not defer to the category`)
  }
})

test('A5b-0 matrix: the committed artifact is CURRENT (deep check)', () => {
  // The artifact is a durable gate, not a snapshot: the committed generator must
  // deep-compare the regenerated matrix (every row's lines/refs/host-seam/tests/
  // callers/lifecycle/capabilities/classification/owner + the bootstrap content
  // hash) and fail when anything drifted. Running the official CLI here means the
  // gate cannot be forgotten.
  const result = spawnSync(process.execPath, ['scripts/a5b-root-matrix.mjs', '--check'], {
    cwd: REPO_ROOT,
    encoding: 'utf8',
  })
  assert.equal(
    result.status,
    0,
    `the ownership matrix is stale — regenerate it with \`node scripts/a5b-root-matrix.mjs --write\`:\n${result.stdout}${result.stderr}`,
  )
})

test('A5b-0 matrix: the residual ownership ledger is exact', () => {
  const residual = matrix.rows.filter((r) => r.classification.startsWith('MUST_MOVE:')).map((r) => r.name).sort()
  assert.deepEqual(
    residual,
    [...RESIDUAL_LEDGER].sort(),
    'the MUST_MOVE residual is an exact, reviewed set: a NEW unowned declaration must be classified (KEEP_BOOTSTRAP with a §7.6.1 reason) or moved, and a landed move must update this ledger in the same slice',
  )
})
