/**
 * Renderer-neutral Focus presentation projection.
 *
 * The Focus projection over one windowed transcript (plan §12/§33): a turn with
 * an initial prompt is grouped as `user(s) -> FocusActivity`; a turn with only
 * same-turn steers starts with `FocusActivity` and keeps those steers in
 * process order. A turn woken by injected-context keeps that LEADING prefix at
 * its original foundation position before the Thought. Collapsed turns HIDE
 * process rows (a committed pre-steer answer is the explicit exception) and
 * expanded turns restore raw chronology with the final assistant held back.
 *
 * This module owns the pure policy only. The PiTui disclosure card, its width
 * formatting, its theme/icon chrome and its live duration provider live in
 * `tui/components/transcript/focus-activity.ts`; TuiApp keeps the mutable
 * expansion state and materializes the blocks.
 * @module @xmoon76/dsh-pi-tui/tui/transcript/focus-projection
 */

import {
  assistantBlocksVisibleNow,
  assistantCommittedBeforeSteer,
  assistantLatestStepOf,
  assistantStepOf,
  type TurnActivity,
  type TranscriptMessage,
} from '../../transcript.ts'
import { isSurfacedContext, isSurfacedInteractionTool } from '../../transcript-semantics.ts'
import { isNoticeContext } from './context-structure.ts'
import { projectTranscriptStructure, type TranscriptStructureBlock, type TranscriptWorkSpan } from './structure.ts'
import type { TranscriptContainerPath } from './container-owner.ts'
import {
  addCompactActionStats,
  compactActionSourceOf,
  latestCompactAction,
  newCompactActionStats,
  type CompactActionSource,
  type CompactActionStats,
  type CompactActionStatsAccumulator,
} from './process-summary.ts'

/**
 * The Focus presentation projection over one windowed transcript (plan
 * §12/§33): a turn with an initial prompt is grouped as
 * `user(s) → FocusActivity`; a turn with only same-turn steers starts with
 * `FocusActivity` and keeps those steers in process order. A turn woken by
 * injected-context keeps that LEADING prefix at its original foundation
 * position before the Thought. Expanded process/final and compaction rows
 * follow, so the raw TranscriptMessage union is never polluted with a fake
 * `focus-activity` kind and the session data stays lossless.
 *
 * Collapsed turns HIDE process rows — thinking, tool, ordinary system/process
 * rows and ordinary intermediate-assistant — so they cannot leak through
 * Ctrl+O/Alt+T (plan §15.2). A committed pre-steer answer is the explicit
 * persistent-row exception. Human user rows and injected context marked
 * `context:true` are persistent input/context rows and remain visible before
 * the Thought in their raw relative order. The final assistant only appears
 * after the authoritative `turn/end` (plan §13.1) and never duplicates in the
 * expanded view (it stays at its chronological position).
 * @param messages - the windowed transcript.
 * @param activities - the folder's per-turn activities (same fold state).
 * @param expandedTurns - the user's expansion choices (live running turns
 *   included — plan §2.3).
 * @param focusMode - whether Focus is on (off = the normal projection).
 */
export type FocusProjectedBlock =
  | {
    kind: 'message'
    message: TranscriptMessage
    truncated?: boolean
    /**
     * The outer-to-inner semantic container ancestry of this row, generated by
     * the projection that produced it (never inferred from screen geometry). A
     * row revealed by an expanded Thought carries `[focus-root]`; a row inside
     * a nested canonical Work span carries `[focus-root, work]`. Persistent
     * input rows (user / surfaced context / settled interaction) and the held
     * back final carry NO path — they are not owned by the Thought.
     */
    containerPath?: TranscriptContainerPath
  }
  | {
    kind: 'activity'
    activity: TurnActivity
    /**
     * The presentation OCCURRENCE identity of this Thought block: the first
     * `TranscriptMessage` of the consecutive same-turn run it summarizes.
     * A turn is NOT a sufficient identity — a turn-less window entry can
     * split one turn into several runs, each with its own hidden rows, Action
     * winner and component. This is the same stable occurrence-owner pattern
     * the Work span and Context cluster already use; the SEMANTIC disclosure
     * identity (Ctrl+O, click ownership, `focusExpandedTurns`,
     * `containerPath`) stays the turn number.
     */
    owner: TranscriptMessage
    /**
     * The turn-level Action aggregate the Focus header renders (addendum v2
     * §17/§18): derived ONCE from the turn group's canonical Process
     * evidence — independent of collapsed/expanded state and search reveals
     * (a temporary reveal must not change `7 actions`). Presentation-only:
     * never stored on `TurnActivity`, never persisted.
     */
    actionStats: CompactActionStats
    /**
     * The presentation-only collapsed Action source (addendum v2
     * §19): derived from the SAME transcript rows this projection hides
     * under the collapsed Thought root — never stored on `TurnActivity`
     * (§14). Absent when no eligible hidden Process evidence exists (or
     * the Thought is expanded, where no preview body renders).
     */
    action?: CompactActionSource
  }
  | {
    /**
     * A canonical Work span materialized inside the expanded Thought. F6 keeps
     * the span as a container (instead of flattening its members) so the owner
     * is preset-neutral and the Work header can be disclosed independently.
     */
    kind: 'work'
    span: TranscriptWorkSpan
    focusOwnerTurn: number
    /** The outer-to-inner ancestor of the Work container (set when TuiApp
     * materializes the nested header). */
    containerPath?: TranscriptContainerPath
  }

/**
 * The Focus projection TURN of one row — the ONE authority `projectFocus` and
 * its grouping helpers share. A COMMAND row has NO projection turn: it is a
 * turn-less control-plane row (`kind: 'command'` carries no `turn` field at
 * all). A CORRELATED manual compaction is turn-less too: once its combined
 * `/compact` owner is established it is a standalone control boundary, so the
 * projection must not re-absorb the card into the preceding turn group — the
 * collapsed Focus reorder would otherwise lift it above the turn's held-back
 * final and invert the real chronology (`assistant final` → `Context
 * compacted`). Treating turn-less rows as BOUNDARIES makes the projection
 * agree with the fold: `process A -> Thought A`, `command -> standalone`,
 * `process B -> Thought B`. Both runs may still belong to one model turn (the
 * run-owner component cache supports that), and the semantic disclosure
 * identity stays the turn number.
 */
function focusProjectionTurnOf(message: TranscriptMessage): number | undefined {
  if (message.kind === 'command') return undefined
  if (message.kind === 'compaction' && message.sourceCommand !== undefined) return undefined
  return 'turn' in message ? message.turn : undefined
}

/**
 * The Thought block for one turn: the caller-resolved TURN-LEVEL Action
 * stats (addendum v2 §18) plus — collapsed only (`hidden !== undefined`) —
 * the presentation-only Action source. `latestCompactAction` picks the
 * latest eligible candidate among EXACTLY the rows the collapsed projection
 * hides under the root, so nothing already visible outside (a committed
 * answer, the held-back final, a post-Thought notice) can duplicate itself
 * in the Action slot.
 */
function focusActivityBlock(
  activity: TurnActivity | undefined,
  owner: TranscriptMessage,
  actionStats: CompactActionStats,
  hidden: readonly TranscriptMessage[] | undefined,
): FocusProjectedBlock[] {
  if (activity === undefined) return []
  const action = hidden === undefined ? undefined : latestCompactAction(hidden)
  return [action === undefined
    ? { kind: 'activity', activity, owner, actionStats }
    : { kind: 'activity', activity, owner, actionStats, action }]
}

/** The empty action aggregate for a turn with no eligible Process evidence:
 * shared so the absent case allocates nothing per block. */
const EMPTY_ACTION_STATS: CompactActionStats = { total: 0, types: new Map() }

/**
 * One linear pass over the window: each turn's WHOLE-TURN action aggregate
 * (addendum v2 §18). Focus stats describe the turn, not the row run: a
 * turn-less entry can split one turn into separate consecutive runs
 * ({@link consecutiveTurnGroup}), and every Thought block of that turn must
 * still report the same turn-level number — never merely its own run's.
 * A search reveal / disclosure state cannot change it because none of them
 * participate here. O(n) once per projection, never a per-frame rescan of an
 * unchanged window.
 */
function focusActionStatsByTurn(messages: readonly TranscriptMessage[]): Map<number, CompactActionStats> {
  const accumulators = new Map<number, CompactActionStatsAccumulator>()
  for (const message of messages) {
    if (!('turn' in message)) continue
    const source = compactActionSourceOf(message)
    if (source === undefined) continue
    let accumulator = accumulators.get(message.turn)
    if (accumulator === undefined) {
      accumulator = newCompactActionStats()
      accumulators.set(message.turn, accumulator)
    }
    addCompactActionStats(accumulator, source)
  }
  const byTurn = new Map<number, CompactActionStats>()
  for (const [turn, accumulator] of accumulators) byTurn.set(turn, accumulator)
  return byTurn
}

/**
 * Project one transcript window into Focus presentation blocks. Collapsed
 * Focus summarizes causal input and opening foundation BEFORE the Thought,
 * renders a durable mid-turn `form:'notice'` AFTER the Thought (visible
 * process feedback, never inside the hidden Action candidate set), and
 * hides ordinary Process inside the collapsed root. Expanded Focus restores
 * the exact raw chronology.
 */
export function projectFocus(
  messages: readonly TranscriptMessage[],
  activities: ReadonlyMap<number, TurnActivity>,
  expandedTurns: ReadonlySet<number>,
  focusMode: boolean,
): FocusProjectedBlock[] {
  if (!focusMode) return messages.map(message => ({ kind: 'message', message }))
  const actionStatsByTurn = focusActionStatsByTurn(messages)
  const out: FocusProjectedBlock[] = []
  let index = 0
  while (index < messages.length) {
    const message = messages[index]!
    const turn = focusProjectionTurnOf(message)
    if (turn === undefined) {
      // Window summaries, standalone command rows and other turn-less entries
      // pass through as standalone blocks (a command acts as a Process-run
      // boundary, so the surrounding Thought runs stay separate).
      out.push({ kind: 'message', message })
      index += 1
      continue
    }
    // One turn's consecutive message run.
    const group = consecutiveTurnGroup(messages, index, turn)
    index += group.length
    const activity = activities.get(turn)
    const actionStats = actionStatsByTurn.get(turn) ?? EMPTY_ACTION_STATS
    const expanded = expandedTurns.has(turn)
    // The final assistant is decided ONCE from the exact last assistant
    // row (shared by the expanded and collapsed branches — one semantic,
    // never two drifting copies).
    const final = finalAssistantSelection(activity, group)
    const isCommittedAnswer = (member: TranscriptMessage): boolean =>
      activity !== undefined && assistantCommittedBeforeSteer(activity, member)
    if (expanded) {
      // The open Thought reveals the FULL process in ORIGINAL order —
      // compaction cards included at their chronological position — with
      // the final assistant held back and appended LAST (a max-tokens
      // turn's `max tokens reached` system row must never land after the
      // final: the settled order is User → Thought → process → final).
      // The THOUGHT-LEAD boundary precedes the Thought: rows before the
      // turn's FIRST non-steer user (injected context) stay in place
      // and that initial user itself stays above the Thought; every later
      // user/steer or surfaced-context row returns to its chronological
      // position (plan: expanded chronology — the projection reorders, never
      // the session events). With a non-steer user, the first such row is the
      // compatibility boundary; when every user is a steer, the boundary
      // falls back to the end of the LEADING injected-context prefix, so an
      // inject-woken turn keeps its foundation before the Thought (never a
      // scan of mid-process system rows). Consecutive users after the
      // boundary stay in chronological order; they are not a multi-row
      // initial prompt (plan: no adjacency guessing). Every revealed
      // ordinary process row carries the owner-turn collapse mark; committed
      // pre-steer answers, user rows, surfaced context, lead foundation rows,
      // and the FINAL assistant stay unmarked (clicking them must not collapse
      // the Thought — review P2).
      const boundary = focusThoughtLeadBoundary(group)
      for (const member of group.slice(0, boundary)) {
        out.push({ kind: 'message', message: member })
      }
      if (activity !== undefined) out.push(...focusActivityBlock(activity, group[0]!, actionStats, undefined))
      const emitTailRow = (member: TranscriptMessage): void => {
        if (isFocusPersistentInputRow(member)) {
          out.push({ kind: 'message', message: member })
          return
        }
        if (final !== undefined && member === final.message) return
        if (isCommittedAnswer(member)) {
          out.push({ kind: 'message', message: member })
          return
        }
        out.push({ kind: 'message', message: member, containerPath: [{ kind: 'focus-root', turn }] })
      }
      // The tail consumes the SAME canonical segmentation as Compact/Full
      // (`transcript-projection.ts`), computed over the UNFILTERED tail so the
      // held-back final never changes raw adjacency. A canonical Work span is
      // emitted as a nested container block (F6) and materialized by TuiApp
      // according to the effective Work disclosure; the TuiApp cluster
      // substitution consumes the same canonical cluster identity at its
      // Focus-projected position.
      for (const block of focusExpandedTailStructure(group, boundary)) {
        if (block.kind === 'work') {
          out.push({ kind: 'work', span: block.span, focusOwnerTurn: turn })
        } else if (block.kind === 'context-cluster') {
          for (const member of block.cluster.members) emitTailRow(member)
        } else {
          emitTailRow(block.message)
        }
      }
      if (final !== undefined) {
        out.push(final.truncated ? { kind: 'message', message: final.message, truncated: true } : { kind: 'message', message: final.message })
      }
      continue
    }
    // Collapsed Focus summarizes persistent input/context rows before the
    // Thought in their raw relative order. Both human user/steer rows and
    // injected context marked `context:true` are persistent; all ordinary
    // process rows stay hidden inside the Thought. A MID-TURN
    // `form:'notice'` is the visible exception (see
    // {@link collapsedFocusRowDisposition}): it renders AFTER the Thought as
    // a post-thought row, never inside the hidden Action candidate set. A
    // committed pre-steer answer is the other exception: from that exact raw
    // boundary onward, preserve the persistent rows and answer in chronology
    // so the answer cannot be swallowed by the Thought or move when the
    // disclosure changes.
    //
    // The collapsed Action source (addendum v2 §19/§42) is selected
    // from EXACTLY the rows this projection hides under the Thought root —
    // the emit loops below record them — so a committed answer, the
    // held-back final and every visible persistent boundary can never
    // duplicate themselves in the Action slot.
    const leadBoundary = focusThoughtLeadBoundary(group)
    const firstCommittedIndex = group.findIndex(isCommittedAnswer)
    const hidden: TranscriptMessage[] = []
    // Collect first, emit once: the pre-thought rows, the post-thought rows
    // and the hidden Action candidates of one group.
    const preThought: TranscriptMessage[] = []
    const postThought: TranscriptMessage[] = []
    if (firstCommittedIndex < 0) {
      for (let index = 0; index < group.length; index += 1) {
        const member = group[index]!
        const disposition = collapsedFocusRowDisposition(member, index, leadBoundary)
        if (disposition === 'pre-thought' || disposition === 'post-thought') {
          (disposition === 'pre-thought' ? preThought : postThought).push(member)
        } else if (member.kind !== 'compaction' && member !== final?.message) {
          hidden.push(member)
        }
      }
      out.push(...preThought.map(member => ({ kind: 'message', message: member }) as FocusProjectedBlock))
      out.push(...focusActivityBlock(activity, group[0]!, actionStats, hidden))
      out.push(...postThought.map(member => ({ kind: 'message', message: member }) as FocusProjectedBlock))
      // Compaction cards keep their existing lifecycle in the collapsed
      // view (plan §12.3 v1 — never hidden into the Thought).
      for (const member of group) {
        if (member.kind === 'compaction') out.push({ kind: 'message', message: member })
      }
    } else {
      const beforeCommitted = group.slice(0, firstCommittedIndex)
      for (let index = 0; index < beforeCommitted.length; index += 1) {
        const member = beforeCommitted[index]!
        const disposition = collapsedFocusRowDisposition(member, index, leadBoundary)
        if (disposition === 'pre-thought' || disposition === 'post-thought') {
          (disposition === 'pre-thought' ? preThought : postThought).push(member)
        } else if (member.kind !== 'compaction') {
          hidden.push(member)
        }
      }
      // The post-boundary emission is decided FIRST (pure) so the Action
      // selection sees the whole hidden scope before the Thought renders.
      // The committed-answer fence is preserved: from the first committed
      // answer onward every persistent row and the answer keep their raw
      // chronology (they are neither hoisted above the Thought nor moved
      // across their semantic boundary).
      const postCommitted: TranscriptMessage[] = []
      for (let index = firstCommittedIndex; index < group.length; index += 1) {
        const member = group[index]!
        if (final !== undefined && member === final.message) continue
        const disposition = collapsedFocusRowDisposition(member, index, leadBoundary)
        if (disposition !== 'hidden' || member.kind === 'compaction' || isCommittedAnswer(member)) {
          postCommitted.push(member)
        } else {
          hidden.push(member)
        }
      }
      out.push(...preThought.map(member => ({ kind: 'message', message: member }) as FocusProjectedBlock))
      out.push(...focusActivityBlock(activity, group[0]!, actionStats, hidden))
      out.push(...postThought.map(member => ({ kind: 'message', message: member }) as FocusProjectedBlock))
      for (const member of beforeCommitted) {
        if (member.kind === 'compaction') out.push({ kind: 'message', message: member })
      }
      for (const member of postCommitted) {
        out.push({ kind: 'message', message: member })
      }
    }
    // The collapsed final: only after the authoritative turn/end.
    if (final !== undefined) {
      out.push(final.truncated ? { kind: 'message', message: final.message, truncated: true } : { kind: 'message', message: final.message })
    }
  }
  return out
}

/**
 * The canonical structural blocks the expanded Focus TAIL consumes: one turn
 * group from its Thought-lead boundary onward. The held-back final is included,
 * so cluster membership is computed from exactly the raw adjacency the window
 * would give. `projectFocus` emits a canonical Work span as a nested `work`
 * block (F6); this exported seam lets the convergence oracle compare
 * Work/cluster boundary IDENTITY (owner and member objects) instead of display
 * strings (plan §25).
 * @param group - one turn's consecutive raw messages.
 * @param boundary - the group's Thought-lead boundary ({@link focusThoughtLeadBoundary}).
 *   Passed in so one expanded group computes the boundary once.
 */
export function focusExpandedTailStructure(group: readonly TranscriptMessage[], boundary: number): TranscriptStructureBlock[] {
  return projectTranscriptStructure(group.slice(boundary))
}

/** Find the Assistant entry that owns the structural latest step. A late
 * durable message can append after newer process evidence, so physical array
 * order is not a reliable final-answer identity. */
function assistantForStep(
  group: readonly TranscriptMessage[],
  step: number,
): Extract<TranscriptMessage, { kind: 'assistant' }> | undefined {
  for (let index = group.length - 1; index >= 0; index -= 1) {
    const member = group[index]
    if (member?.kind === 'assistant' && assistantStepOf(member) === step) return member
  }
  return undefined
}

/** Rows that remain visible outside the collapsed Thought as persistent
 * input/context boundaries. The semantic class stays Context for injected
 * rows; this predicate only controls disclosure behavior. A SETTLED
 * surfaced-interaction card (question / Plan review) is human-decision
 * evidence, so it is hoisted out of the collapsed Working exactly like a
 * user/steer row; expanded Focus restores it at its raw chronology. */
function isFocusPersistentInputRow(message: TranscriptMessage): boolean {
  // A COMMAND is standalone `control` evidence, not Process: it is a
  // turn-less session-level lifecycle whose settled result is user feedback.
  // It must therefore stay VISIBLE outside the collapsed Thought — like a
  // user/steer row or a settled interaction — instead of being hidden as
  // process and/or claimed by the Thought's Action slot.
  // A TOOL_NOT_STARTED diagnostic is the ONE attention row without a
  // turn-level presentation of its own: the other attention origins
  // (turn-error / turn-interrupted / turn-max-tokens) are already
  // presented by the Focus header status label and the collapsed Error
  // slot, so hoisting their synthetic rows would only duplicate the same
  // fact. The not-started recovery is invisible there — it must stay a
  // standalone visible diagnostic while collapsed and return to its raw
  // chronology when the Thought opens.
  return message.kind === 'user' || isSurfacedContext(message) || isSurfacedInteractionTool(message)
    || message.kind === 'command'
    || (message.kind === 'tool' && message.origin === 'tool-not-started')
}

/**
 * The collapsed-Focus disposition of one row: where it renders relative to
 * the Thought (or that it does not render at all while collapsed).
 *
 * Position-aware plus semantic: a MID-TURN `form:'notice'` (a background job
 * or subagent settling while the Agent already works) is process feedback
 * that belongs AFTER the Thought, not causal input hoisted before it; a
 * notice inside the turn's OPENING foundation (`index < leadBoundary`)
 * explains why the turn started and stays BEFORE the Thought. Every other
 * persistent input/context row keeps its existing pre-Thought behavior, and
 * ordinary Process stays hidden inside the collapsed Thought (restored in
 * raw chronology when the Thought opens). The decision reads the semantic
 * `form` and raw position, never a source kind or plugin name; `Compact` and
 * `Full` do not route through here.
 */
type CollapsedFocusRowDisposition = 'pre-thought' | 'post-thought' | 'hidden'

function collapsedFocusRowDisposition(
  message: TranscriptMessage,
  index: number,
  leadBoundary: number,
): CollapsedFocusRowDisposition {
  if (!isFocusPersistentInputRow(message)) return 'hidden'
  if (index >= leadBoundary && isNoticeContext(message)) return 'post-thought'
  return 'pre-thought'
}

/**
 * One turn's maximal run of CONSECUTIVE same-turn rows starting at `start`.
 * A turn-less entry (window summary) may SPLIT a turn into separate runs, and
 * the projection folds each run independently — this helper is shared by the
 * projection and the collapsed visibility predicate so their index and
 * `focusThoughtLeadBoundary` math can never diverge on a non-monotonic window.
 * @param messages - the transcript window.
 * @param start - the run's first index.
 * @param turn - the run's turn number.
 */
function consecutiveTurnGroup(messages: readonly TranscriptMessage[], start: number, turn: number): TranscriptMessage[] {
  const group: TranscriptMessage[] = [messages[start]!]
  let index = start + 1
  while (index < messages.length) {
    const next = messages[index]!
    // `focusProjectionTurnOf` — never the raw `turn` — so a turn-less
    // standalone row cannot join (or split) the run it merely sits in.
    if (focusProjectionTurnOf(next) !== turn) break
    group.push(next)
    index += 1
  }
  return group
}

/** The end of the turn's LEADING injected-context prefix used only for
 * expanded Thought insertion. Consecutive `kind === 'system'` rows carrying
 * the source-derived `context` marker at the very start of the group count as
 * the opening turn foundation. Other `kind: 'system'` rows (llm/retry,
 * max-tokens) are orchestration, not foundation — they must stay process
 * content, never lifted before the Thought. Mid-process system rows are never
 * included in this expanded lead boundary; collapsed visibility uses
 * isFocusPersistentInputRow instead. */
function leadingInjectedContextPrefixEnd(group: readonly TranscriptMessage[]): number {
  let end = 0
  while (true) {
    const member = group[end]
    if (member === undefined || member.kind !== 'system' || member.context !== true) break
    end += 1
  }
  return end
}

/** The Thought-lead boundary of one turn group: the index AFTER the
 * turn's FIRST unmarked user row AND the surfaced Context rows that
 * immediately follow it. Rows before it (injected context) and the opening
 * foundation (initial user plus its adjacent injected context) stay above the
 * Thought; every later row (same-turn steers included) returns to its
 * chronological position. A turn whose user rows are all marked same-turn
 * steers has no opening human prompt: the boundary falls back to the end of
 * the LEADING injected-context prefix, so an inject-woken turn keeps its
 * foundation before the Thought (never a scan of mid-process system rows, and
 * never orchestration rows like llm/retry). Without steer metadata, the first
 * user remains the initial-prompt fallback; consecutive users are queue/steer
 * input, not a multi-row initial prompt. */
export function focusThoughtLeadBoundary(group: readonly TranscriptMessage[]): number {
  const firstInitialUserIndex = group.findIndex(
    member => member.kind === 'user' && member.steer !== true,
  )
  let end = firstInitialUserIndex >= 0
    ? firstInitialUserIndex + 1
    : leadingInjectedContextPrefixEnd(group)
  // The opening foundation continues through immediately-following surfaced
  // Context rows (the provider's opening snapshot/catalog burst), so it never
  // lands below the Thought. A later Context row separated by Process rows is
  // mid-turn and keeps its chronological position.
  while (true) {
    const member = group[end]
    if (member === undefined || !isSurfacedContext(member)) break
    end += 1
  }
  return end
}

/** Whether one Assistant entry has semantic/finalized content or an explicit
 * delivered-file tail. Pending display-only open-opaque rows remain transcript
 * evidence but cannot become a completed/max-token final; finalized generic
 * blocks stay eligible. */
function assistantRenderable(assistant: Extract<TranscriptMessage, { kind: 'assistant' }>): boolean {
  if (assistant.displayBlocks?.some(block => block.kind === 'open-opaque') === true) return false
  if (assistant.deliverables !== undefined && assistant.deliverables.length > 0) return true
  if (assistant.content !== undefined) return assistantBlocksVisibleNow(assistant.content)
  return assistant.text.trim() !== ''
}

/** The turn's final assistant selection: only after the authoritative
 * turn/end, only for a reason the system presents output (completed /
 * max-tokens), and only when the Assistant owning the structural latest step
 * has semantic/finalized content or explicit delivered files. An empty or
 * pending latest step without either yields NO final — never an earlier assistant
 * (review fix). The max-tokens final carries
 * the truncated marker (plan §13.8). */
function finalAssistantSelection(
  activity: TurnActivity | undefined,
  group: readonly TranscriptMessage[],
): { message: Extract<TranscriptMessage, { kind: 'assistant' }>; truncated: boolean } | undefined {
  if (activity === undefined || !activity.completed) return undefined
  const reason = activity.reason?.kind
  if (reason !== 'completed' && reason !== 'max-tokens') return undefined
  // The exact authoritative assistant may be retained internally but hidden
  // from the normal transcript projection; never fall back to an earlier row.
  const latestStep = assistantLatestStepOf(activity)
  if (activity.lastAssistantVisible === false || latestStep === undefined) return undefined
  const last = assistantForStep(group, latestStep)
  // Interrupted prefixes and display-only pending rows are process evidence,
  // never a completed/max-token final answer, even when a malformed log reports
  // a successful reason.
  if (last === undefined || last.interrupted === true || !assistantRenderable(last)) return undefined
  return { message: last, truncated: reason === 'max-tokens' }
}
