/**
 * Shared forked-agent creation for `/fork` and conversation rewind.
 *
 * Both features create a child session from a seed through ONE chain
 * (plan §6.2): resolve the source's recorded preset → compose → agents.create
 * with `parentSession` + `seedLength` metadata → the caller swaps to it.
 * Only the seed computation differs (`forkSeed` for `/fork`, `rewindSeed`
 * for rewind), so the metadata, preset/provider/model inheritance and cwd
 * rules can never drift between the two surfaces.
 *
 * `commitRewind` is the rewind selection workflow (stale check → create →
 * swap COMMIT → restore the prompt), with ONE authoritative pre-create
 * stale gate: it MUST run inside the caller's session-transition gate, so
 * no other transition can interleave and a stale selection never creates a
 * child at all — once the create succeeds, the child is committed (no
 * post-create disposal of a "ghost" child exists).
 * @module @xmoon76/dsh-pi-tui/session-fork
 */

import { randomUUID } from 'node:crypto'
import { SessionId } from '@deepseek-ai/dsh-session'
import type { SessionEvent } from '@deepseek-ai/dsh-session'
import type { Agent, AgentHandle } from '@deepseek-ai/dsh-agent'
import { resolveSessionPreset } from '@deepseek-ai/dsh-agent-presets'
import { rewindSeed, type RewindCandidate } from './rewind.ts'
import type { CreateSessionRequest, ResumeSessionRequest, SessionHandle } from './runtime/session-lifecycle-port.ts'
import { safeErrorMessage } from './error-boundary.ts'

/** The narrow host surface child creation needs (plan §23) — the runner
 * satisfies it structurally. */
export interface ForkAgentHost {
  /** The live session's workspace (its header cwd), never a captured value. */
  sessionCwd(): string
  /** The session lifecycle port `/new` and `/fork` create sessions
   * through: semantic requests only (no callbacks — the Direct adapter
   * resolves the preset composition internally). */
  agents: {
    create(options: CreateSessionRequest): Promise<SessionHandle>
    resume(options: ResumeSessionRequest): Promise<SessionHandle>
  }
}

/**
 * Create one forked agent: the source's recorded preset, the source's
 * workspace cwd, the source's provider/model, and `parentSession` +
 * `seedLength` metadata (the exact chain `/fork` used before the
 * extraction). The child's session id is PRE-GENERATED by the caller so
 * the transition can acquire its open lock BEFORE the create publishes it
 * (review round 6: every fallible ownership operation happens before the
 * durable child exists).
 *
 * The preset rides the semantic create request as the CONCRETE preset id
 * (migration M1.11): the Direct adapter composes the setup internally from
 * that id — a composition/setup callback never crosses this seam. `undefined`
 * = the deployment default (a rosterless deployment records no preset).
 * @param host - the fork host surface.
 * @param source - the session being forked from (never modified).
 * @param seed - the child's seed events (completed-turn prefix).
 * @param sessionId - the pre-generated child session id.
 * @param presetId - the concrete preset id the child composes on.
 * @returns the created agent handle (NOT yet committed).
 */
export async function createForkedAgent(
  host: ForkAgentHost,
  source: Agent,
  seed: readonly SessionEvent[],
  sessionId: SessionId,
  presetId?: string,
): Promise<SessionHandle> {
  // Source-deterministic cwd, captured BEFORE the first await: a concurrent
  // surface switch between the compose await and the create must never mix
  // parent=A with cwd=B (review P2). The SOURCE's own workspace wins (the
  // child is a branch of that session); an empty/missing header cwd falls
  // back to the live surface cwd — inside the transition gate the two are
  // identical anyway, which makes the helper independent of that invariant.
  const cwd = source.session.header.cwd || host.sessionCwd()
  // The child inherits the parent's recorded preset (official fork
  // semantics: forkComposition = composeAgent(resolveSessionPreset(source))).
  return host.agents.create({
    sessionId: String(sessionId),
    meta: {
      cwd,
      ...(presetId === undefined ? {} : { agentPreset: presetId }),
      parentSession: source.session.id,
      seedLength: seed.length,
    },
    provider: source.options.provider,
    model: source.options.model,
    agentPreset: presetId,
    seed,
  })
}

/** The live surface identity a rewind commit checks against (stale gates). */
export interface RewindLiveIdentity {
  sessionId: string | undefined
  generation: number
}

/** Whether a captured rewind identity still matches the live surface: a
 * sessionless surface (`sessionId: undefined`) can never match a captured
 * source, so a surface that became sessionless is refused just like a
 * switched one. Pure so the race is unit-testable without the runner. */
export function isRewindIdentityCurrent(live: RewindLiveIdentity, expected: RewindLiveIdentity): boolean {
  return live.sessionId === expected.sessionId && live.generation === expected.generation
}

/** The commit host: the fork host plus the preset composition seam (the
 * rewind flow's Direct-owned composition resolution) and the unified
 * transition machinery. */
export interface RewindCommitHost extends ForkAgentHost {
  /** Compose one preset (undefined = the deployment default) — the
   * rewind flow's Direct-owned ownership path: the composition's SETUP
   * callback stays runner-side, only the resolved preset ID rides the
   * semantic create (migration M1.11). */
  compose(presetId?: string): Promise<{
    agentPreset?: string
    setup: (agentCtx: import('@deepseek-ai/cordis').Context) => Promise<void> | void
  }>
  /** The live surface identity, re-read at every gate. */
  liveIdentity(): RewindLiveIdentity
  /**
   * The unified session-transition transaction (the runner's
   * `transitionTo`): the OLD session is flushed BEFORE `create` runs, the
   * commit is a synchronous critical section, and once `create` succeeds
   * the child is published — there is NO failure path afterwards that may
   * be interpreted as "the child never happened" (there is no durable
   * rollback primitive; `dispose()` stops an agent but never deletes a
   * persisted session). Failures can therefore only occur BEFORE the
   * create: `prepare` throws (the caller's own gates — e.g. the stale
   * identity check) or `create` throws.
   */
  transitionTo<T>(steps: {
    /** The child's PRE-GENERATED session identity (MANDATORY): the
     * transaction reserves its lease BEFORE the DSH call (while the old
     * lock is still held), so a refusal aborts with zero child side
     * effects; once the DSH boundary is crossed, a failure PINNS the
     * target — never released, never retried. */
    target: { id: string; header?: { cwd?: string } }
    /** Whether the target is a FRESH session: the target lock must settle
     * as acquired, or the transaction aborts before the create. */
    fresh?: boolean
    prepare?: () => Promise<void> | void
    create: () => Promise<T>
  }): Promise<{ ok: true; next: T } | { ok: false; message: string }>
  /** Restore the selected prompt into the editor — runs ONLY after the
   * transaction committed (a failed prepare/create never overwrites the
   * draft). */
  replaceDraft(text: string): void
}

/** The settled outcome of a rewind commit. */
export type RewindCommitOutcome =
  | { kind: 'rewound'; sessionId: string; turn: number; hasNonTextContent: boolean }
  | { kind: 'stale' }
  | { kind: 'failed'; message: string }

/**
 * Commit one rewind selection: fork the source before the candidate's turn,
 * commit the child, then restore the selected prompt into the editor.
 *
 * Transaction contract (review round 2 — the durable-ghost blocker): the
 * stale check and the seed derivation run BEFORE anything is created; the
 * create itself happens inside the runner's unified transaction, which
 * flushes the old session first, commits synchronously, and never rolls a
 * published child back. A stale selection therefore never creates a child
 * at all, a failed create leaves the source untouched, and once the child
 * exists it IS the surface. The source session is never modified at any
 * point.
 *
 * MUST run inside the caller's session-transition gate (the runner wraps
 * the commit in the gate): with the gate held, no other transition can
 * interleave, so the pre-create stale check is authoritative.
 *
 * @param host - the commit host.
 * @param source - the live agent whose session the picker listed.
 * @param candidate - the selected rewind point.
 * @param expected - the source identity captured when the picker opened
 *   (a selection must not commit into a surface another path has switched
 *   away from).
 * @returns the outcome; `stale` when the source no longer owns the surface
 *   (detected before any child is created).
 */
export async function commitRewind(
  host: RewindCommitHost,
  source: Agent,
  candidate: RewindCandidate,
  expected: RewindLiveIdentity,
): Promise<RewindCommitOutcome> {
  // Stale gate BEFORE anything is created (inside the transition gate a
  // switch cannot interleave, so this is authoritative): a stale selection
  // never creates — and therefore never publishes — a child.
  const identity = host.liveIdentity()
  if (!isRewindIdentityCurrent(identity, expected)) {
    return { kind: 'stale' }
  }
  let seed: readonly SessionEvent[]
  try {
    seed = rewindSeed(source.session.events, candidate)
  } catch (error) {
    // The point vanished or the log turned malformed since the picker
    // opened: report, never create a child.
    return { kind: 'failed', message: safeErrorMessage(error) }
  }
  // The unified transaction: old-session quiesce+flush → TARGET lock
  // (pre-generated child id, acquired BEFORE the create — review round 6:
  // every fallible ownership operation happens before the durable child is
  // published) → create → synchronous commit → best-effort retire.
  // Failures can only happen before the create; once it succeeds the child
  // IS the surface (no ghost, no rollback).
  const sessionId = SessionId(`session-${randomUUID()}`)
  // The composition is resolved ONCE and rides the create as the concrete
  // preset ID (a rejected create is NEVER retried — the first DSH call may
  // have left a hidden lifecycle, so the target is PINNED immediately).
  // The composition's SETUP callback stays with the runner (Direct
  // ownership); only the identity crosses into the semantic create
  // (migration M1.11). The preflight compose here is the lock-ORDERING
  // validation (the M1.5 contract): a broken/unknown preset must fail
  // BEFORE the target lock is acquired — the Direct lifecycle's own
  // compose from the same id is the authoritative setup, and composeAgent
  // is deterministic within a process run, so the two resolutions cannot
  // diverge. The preflight is classified like the seed failure: a compose
  // rejection is a `failed` outcome, never an escape.
  let composition: { agentPreset?: string }
  try {
    composition = await host.compose(resolveSessionPreset(source.session))
  } catch (error) {
    return { kind: 'failed', message: safeErrorMessage(error) }
  }
  const result = await host.transitionTo({
    target: {
      id: String(sessionId),
      // The child's lock path needs its workspace: the same source-first
      // rule createForkedAgent uses (the live surface cwd is the fallback).
      header: { cwd: source.session.header.cwd || host.sessionCwd() },
    },
    fresh: true,
    create: () => createForkedAgent(host, source, seed, sessionId, composition.agentPreset),
  })
  if (!result.ok) return { kind: 'failed', message: result.message }
  // The transaction COMMITTED: restore the selected prompt (synchronous,
  // cannot fail — the user sees their historic prompt ready to edit and
  // resend).
  host.replaceDraft(candidate.editorText)
  return {
    kind: 'rewound',
    sessionId: result.next.session.id,
    turn: candidate.turn,
    hasNonTextContent: candidate.hasNonTextContent,
  }
}
